### ISSUE TITLE
Requirement versions

### ISSUE THREAD

**Issue by Awmusic12635** [elderlabs/BetterDisco#2]
Is requiring specific versions actually needed for the packages or would it be possible to add a range of supported values?

**Comment by elderlabs** [comment]
Specific versions are tested and known to be working as far as we're able to confirm. We do not intend to support version ranges at this time. While ranges are nice for bots that may use older versions, it leaves room for errors we may not be able to account for, like the websocket requirement (several issues on their tracker worth the glance), or older version of gevent entirely. Do you have a particular reason to request package ranges?
